let stockProductos = [
    {id: 1, nombre: "Monitor 1", tipo: "Monitor", cantidad: 1, desc: "Monitor LED 144hz", precio: 1200, img: './img/monitor.webp'},
    {id: 2, nombre: "Monitor 2", tipo: "Monitor", cantidad: 1, desc: "Monitor LED 144hz", precio: 1100, img: './img/monitor.webp'},
    {id: 3, nombre: "Monitor 3", tipo: "Monitor", cantidad: 1, desc: "Monitor LED 144hz", precio: 1200, img: './img/monitor.webp'},
    {id: 4, nombre: "Monitor 4", tipo: "Monitor", cantidad: 1, desc: "Monitor LED 144hz", precio: 1400, img: './img/monitor.webp'},
    {id: 5, nombre: "Monitor 5", tipo: "Monitor", cantidad: 1, desc: "Monitor LED 144hz", precio: 1200, img: './img/monitor.webp'},
    {id: 6, nombre: "Monitor 6", tipo: "Monitor", cantidad: 1, desc: "Monitor LED 144hz", precio: 1500, img: './img/monitor.webp'},
    {id: 7, nombre: "Teclado 1", tipo: "Teclado", cantidad: 1, desc: "Teclado Mecanico", precio: 500, img: './img/teclado.jpg'},
    {id: 8, nombre: "Teclado 2", tipo: "Teclado", cantidad: 1, desc: "Teclado Mecanico", precio: 500, img: './img/teclado.jpg'},
    {id: 9, nombre: "Teclado 3", tipo: "Teclado", cantidad: 1, desc: "Teclado Mecanico", precio: 500, img: './img/teclado.jpg'},
    {id: 10, nombre: "Teclado 4", tipo: "Teclado", cantidad: 1, desc: "Teclado Mecanico", precio: 700, img: './img/teclado.jpg'},
    {id: 11, nombre: "Teclado 5", tipo: "Teclado", cantidad: 1,desc: "Teclado Mecanico", precio: 700, img: './img/teclado.jpg'},
    {id: 12, nombre: "Teclado 6", tipo: "Teclado", cantidad: 1, desc: "Teclado Mecanico", precio: 700, img: './img/teclado.jpg'},
    {id: 13, nombre: "Mouse 1", tipo: "Mouse", cantidad: 1, desc: "Mouse Inalambrico", precio: 900, img: './img/mouse.jpg'},
    {id: 14, nombre: "Mouse 2", tipo: "Mouse", cantidad: 1, desc: "Mouse Inalambrico", precio: 1400, img: './img/mouse.jpg'},
    {id: 15, nombre: "Mouse 3", tipo: "Mouse", cantidad: 1, desc: "Mouse Inalambrico", precio: 7000, img: './img/mouse.jpg'},
    {id: 16, nombre: "Mouse 4", tipo: "Mouse", cantidad: 1, desc: "Mouse Inalambrico", precio: 777, img: './img/mouse.jpg'},
    {id: 17, nombre: "Mouse 5", tipo: "Mouse", cantidad: 1, desc: "Mouse Inalambrico", precio: 234, img: './img/mouse.jpg'},
    {id: 18, nombre: "Mouse 6", tipo: "Mouse", cantidad: 1, desc: "Mouse Inalambrico", precio: 155600, img: './img/mouse.jpg'},
    {id: 19, nombre: "Sonido 1", tipo: "Sonido", cantidad: 1, desc: "Los mejores Auriculares del mercado", precio: 1600, img: './img/sonido.jpg'},
    {id: 20, nombre: "Sonido 2", tipo: "Sonido", cantidad: 1, desc: "Los mejores Auriculares del mercado", precio: 3200, img: './img/sonido.jpg'},
    {id: 21, nombre: "Sonido 3", tipo: "Sonido", cantidad: 1, desc: "Los mejores Auriculares del mercado", precio: 2300, img: './img/sonido.jpg'},
    {id: 22, nombre: "Sonido 4", tipo: "Sonido", cantidad: 1, desc: "Los mejores Auriculares del mercado", precio: 5600, img: './img/sonido.jpg'},
    {id: 23, nombre: "Sonido 5", tipo: "Sonido", cantidad: 1, desc: "Los mejores Auriculares del mercado", precio: 1700, img: './img/sonido.jpg'},
    {id: 24, nombre: "Sonido 6", tipo: "Sonido", cantidad: 1, desc: "Los mejores Auriculares del mercado", precio: 800, img: './img/sonido.jpg'},
];